// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Hatchery struct {
	ID          int64         `json:"id"`
	HatcheryID  int64         `json:"hatcheryID"`
	CreatedAt   time.Time     `json:"createdAt"`
	Infertile   sql.NullInt64 `json:"infertile"`
	Early       sql.NullInt64 `json:"early"`
	Middle      sql.NullInt64 `json:"middle"`
	Late        sql.NullInt64 `json:"late"`
	DeadChicks  sql.NullInt64 `json:"deadChicks"`
	AliveChicks sql.NullInt64 `json:"aliveChicks"`
}

type Kuroiler struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	House     string    `json:"house"`
	CreatedAt time.Time `json:"createdAt"`
}

type Production struct {
	ID           int64         `json:"id"`
	ProductionID int64         `json:"productionID"`
	CreatedAt    time.Time     `json:"createdAt"`
	Eggs         sql.NullInt64 `json:"eggs"`
	Dirty        sql.NullInt64 `json:"dirty"`
	WrongShape   sql.NullInt64 `json:"wrongShape"`
	WeakShell    sql.NullInt64 `json:"weakShell"`
	Damaged      sql.NullInt64 `json:"damaged"`
	HatchingEggs sql.NullInt64 `json:"hatchingEggs"`
}
