// Code generated by sqlc. DO NOT EDIT.
// source: production.sql

package db

import (
	"context"
	"database/sql"
)

const createProduction = `-- name: CreateProduction :one
INSERT INTO production (
    eggs,
    dirty,
    wrong_shape,
    weak_shell,
    damaged,
    hatching_eggs
) VALUES (
             $1, $2, $3, $4, $5, $6
         ) RETURNING id, production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs
`

type CreateProductionParams struct {
	Eggs         sql.NullInt64 `json:"eggs"`
	Dirty        sql.NullInt64 `json:"dirty"`
	WrongShape   sql.NullInt64 `json:"wrongShape"`
	WeakShell    sql.NullInt64 `json:"weakShell"`
	Damaged      sql.NullInt64 `json:"damaged"`
	HatchingEggs sql.NullInt64 `json:"hatchingEggs"`
}

func (q *Queries) CreateProduction(ctx context.Context, arg CreateProductionParams) (Production, error) {
	row := q.queryRow(ctx, q.createProductionStmt, createProduction,
		arg.Eggs,
		arg.Dirty,
		arg.WrongShape,
		arg.WeakShell,
		arg.Damaged,
		arg.HatchingEggs,
	)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.CreatedAt,
		&i.Eggs,
		&i.Dirty,
		&i.WrongShape,
		&i.WeakShell,
		&i.Damaged,
		&i.HatchingEggs,
	)
	return i, err
}

const getProduction = `-- name: GetProduction :one
SELECT id, production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs FROM production
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduction(ctx context.Context, id int64) (Production, error) {
	row := q.queryRow(ctx, q.getProductionStmt, getProduction, id)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.CreatedAt,
		&i.Eggs,
		&i.Dirty,
		&i.WrongShape,
		&i.WeakShell,
		&i.Damaged,
		&i.HatchingEggs,
	)
	return i, err
}

const listProduction = `-- name: ListProduction :many
SELECT id, production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs FROM production
WHERE production_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListProductionParams struct {
	ProductionID int64 `json:"productionID"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListProduction(ctx context.Context, arg ListProductionParams) ([]Production, error) {
	rows, err := q.query(ctx, q.listProductionStmt, listProduction, arg.ProductionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Production
	for rows.Next() {
		var i Production
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.CreatedAt,
			&i.Eggs,
			&i.Dirty,
			&i.WrongShape,
			&i.WeakShell,
			&i.Damaged,
			&i.HatchingEggs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
