// Code generated by sqlc. DO NOT EDIT.
// source: production.sql

package db

import (
	"context"
	"database/sql"
)

const createProduction = `-- name: CreateProduction :one
INSERT INTO production (
    eggs,
    dirty,
    wrong_shape,
    weak_shell,
    damaged,
    hatching_eggs
) VALUES (
             $1, $2, $3, $4, $5, $6
) RETURNING production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs, kuroiler_id, rainbowrooster_id, broiler_id, layers_id
`

type CreateProductionParams struct {
	Eggs         sql.NullInt64 `json:"eggs"`
	Dirty        sql.NullInt32 `json:"dirty"`
	WrongShape   sql.NullInt32 `json:"wrongShape"`
	WeakShell    sql.NullInt32 `json:"weakShell"`
	Damaged      sql.NullInt32 `json:"damaged"`
	HatchingEggs sql.NullInt64 `json:"hatchingEggs"`
}

func (q *Queries) CreateProduction(ctx context.Context, arg CreateProductionParams) (Production, error) {
	row := q.queryRow(ctx, q.createProductionStmt, createProduction,
		arg.Eggs,
		arg.Dirty,
		arg.WrongShape,
		arg.WeakShell,
		arg.Damaged,
		arg.HatchingEggs,
	)
	var i Production
	err := row.Scan(
		&i.ProductionID,
		&i.CreatedAt,
		&i.Eggs,
		&i.Dirty,
		&i.WrongShape,
		&i.WeakShell,
		&i.Damaged,
		&i.HatchingEggs,
		&i.KuroilerID,
		&i.RainbowroosterID,
		&i.BroilerID,
		&i.LayersID,
	)
	return i, err
}

const getProduction = `-- name: GetProduction :one
SELECT production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs, kuroiler_id, rainbowrooster_id, broiler_id, layers_id FROM production
WHERE production_id = $1 LIMIT 1
`

func (q *Queries) GetProduction(ctx context.Context, productionID sql.NullInt64) (Production, error) {
	row := q.queryRow(ctx, q.getProductionStmt, getProduction, productionID)
	var i Production
	err := row.Scan(
		&i.ProductionID,
		&i.CreatedAt,
		&i.Eggs,
		&i.Dirty,
		&i.WrongShape,
		&i.WeakShell,
		&i.Damaged,
		&i.HatchingEggs,
		&i.KuroilerID,
		&i.RainbowroosterID,
		&i.BroilerID,
		&i.LayersID,
	)
	return i, err
}

const listProduction = `-- name: ListProduction :many
SELECT production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs, kuroiler_id, rainbowrooster_id, broiler_id, layers_id FROM production
ORDER BY production_id
LIMIT $1
OFFSET $2
`

type ListProductionParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProduction(ctx context.Context, arg ListProductionParams) ([]Production, error) {
	rows, err := q.query(ctx, q.listProductionStmt, listProduction, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Production
	for rows.Next() {
		var i Production
		if err := rows.Scan(
			&i.ProductionID,
			&i.CreatedAt,
			&i.Eggs,
			&i.Dirty,
			&i.WrongShape,
			&i.WeakShell,
			&i.Damaged,
			&i.HatchingEggs,
			&i.KuroilerID,
			&i.RainbowroosterID,
			&i.BroilerID,
			&i.LayersID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduction = `-- name: UpdateProduction :one
UPDATE production
SET
     eggs = $1,
     dirty = $2,
     wrong_shape = $3,
     weak_shell = $4,
     damaged = $5,
     hatching_eggs = $6

WHERE production_id = $1
RETURNING production_id, created_at, eggs, dirty, wrong_shape, weak_shell, damaged, hatching_eggs, kuroiler_id, rainbowrooster_id, broiler_id, layers_id
`

type UpdateProductionParams struct {
	Eggs         sql.NullInt64 `json:"eggs"`
	Dirty        sql.NullInt32 `json:"dirty"`
	WrongShape   sql.NullInt32 `json:"wrongShape"`
	WeakShell    sql.NullInt32 `json:"weakShell"`
	Damaged      sql.NullInt32 `json:"damaged"`
	HatchingEggs sql.NullInt64 `json:"hatchingEggs"`
}

func (q *Queries) UpdateProduction(ctx context.Context, arg UpdateProductionParams) (Production, error) {
	row := q.queryRow(ctx, q.updateProductionStmt, updateProduction,
		arg.Eggs,
		arg.Dirty,
		arg.WrongShape,
		arg.WeakShell,
		arg.Damaged,
		arg.HatchingEggs,
	)
	var i Production
	err := row.Scan(
		&i.ProductionID,
		&i.CreatedAt,
		&i.Eggs,
		&i.Dirty,
		&i.WrongShape,
		&i.WeakShell,
		&i.Damaged,
		&i.HatchingEggs,
		&i.KuroilerID,
		&i.RainbowroosterID,
		&i.BroilerID,
		&i.LayersID,
	)
	return i, err
}
